# Generated by Django 3.1.2 on 2020-11-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagesee',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='seed',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
