# Generated by Django 3.1.2 on 2020-11-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201115_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='see',
        ),
    ]
