# Generated by Django 3.1.2 on 2020-11-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_see'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
