# Generated by Django 3.1.2 on 2020-11-22 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_see'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='see',
            name='name',
        ),
    ]
