# Generated by Django 3.1.2 on 2020-11-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_see_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='See',
        ),
    ]
