# Generated by Django 3.1.2 on 2020-11-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_see'),
    ]

    operations = [
        migrations.DeleteModel(
            name='See',
        ),
    ]
