# Generated by Django 3.1.2 on 2020-11-25 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product2',
        ),
    ]
