# Generated by Django 3.1.2 on 2020-11-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product2',
        ),
    ]
