# Generated by Django 3.1.2 on 2020-12-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleOne', models.CharField(max_length=200, null=True)),
                ('titleTow', models.CharField(max_length=200, null=True)),
                ('imageBlog', models.ImageField(blank=True, null=True, upload_to='')),
                ('textBlog', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product2',
        ),
    ]
