# Generated by Django 3.1.2 on 2020-12-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20201201_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image2Blog',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
