# Generated by Django 3.1.4 on 2020-12-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_orderitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='category',
        ),
    ]
